name: Matrix configuration

on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-22.04, windows-latest]
        images: [hello-world, alpine]
        exclude:
          - os: alpine 
            images: windows-latest
        include:
          - os: amd64/alpine
            images: ubuntu-22.04

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Show Docker Info
        run: docker info

      - name: Run Docker on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}

