name: Exploring Variables and secrets

on: 
    push

env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: urinovshokirjon
    IMAGE_NAME: github-actions-nginx

jobs:

################### environment variables at STEP level ##################  
    
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY }}/$DOCKER_USERNAME/$IMAGE_NAME:latest .

        - name: Docker Login
          env:
            DOCKER_PASSWORD: Sh1785150
          run:  docker login --username=$DOCKER_USERNAME --password=$DOCKER_PASSWORD

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest
