name: Exploring Variables and secrets

on: 
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: "*/1 * * * *"
  # schedule:
  #   - cron: '0 8 * * 1' # Har dushanba 8:00 da
    # push

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:

################### environment variables at STEP level ##################  
    
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest .

        - name: Docker Login
          run:  docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
      needs: docker
      concurrency:
        group: production-deployment
        cancel-in-progress: false
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        timeout-minutes: 1
        run: |
          echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest
          sleep 600s